# Generated by Django 3.2 on 2023-01-25 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tweet',
            name='img',
            field=models.ImageField(blank=True, default='/tweet-images', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
